### ISSUE TITLE
Issue with MySQL URLs in go >= 1.12.8

### ISSUE THREAD

**Issue by willgorman** [xo/dburl#11]
`dburl.Parse` returns an error on MySQL urls with a hostname format like `tcp(host:port)` (as seen in the [examples](https://github.com/go-sql-driver/mysql#examples) for the mysql driver).  

```go
package main

import (
	"github.com/xo/dburl"
)

func main() {
	_, err := dburl.Parse("mysql://user:password@tcp(localhost:3306)/db")
	if err != nil {
		panic(err)
	}
}
```

```sh
bash-5.0$ go1.12.7 run main.go
bash-5.0$ go1.12.8 run main.go
panic: parse mysql://user:password@tcp(mysql:3306)/db: invalid port ":3306)" after host

goroutine 1 [running]:
main.main()
        /Users/will.gorman/main.go:10 +0x63
exit status 2
```

There appears to have been a [recent change](https://github.com/golang/go/commit/61bb56ad63992a3199acc55b2537c8355ef887b6#diff-6c2d018290e298803c0c9419d8739885) to the standard library to more closely follow RFC 3986 that caused this.  

Should dburl handle that case or is that not a style of URL that dburl was intended to support either?

**Comment by kenshaw** [comment]
The example connection strings provided by the MySQL driver package, are for use with the [`sql.Open`](https://golang.org/pkg/database/sql/#Open) call, and would look like the following:

```go
   db, err := sql.Open("mysql", "user:password@tcp(localhost:3306)/db")
```

The `dburl` package attempts to use normal URL semantics for accessing databases. As such, it's worth noting that the error encountered here is the correct error: that's an invalid host name. If you'd like to use the URL semantics with `dburl`, then the code would look something like the following:

```go
   db, err := dburl.Open("mysql://user:pass@host:5123/dbname")
```
