### ISSUE TITLE
Feature Request: redis dsn

### ISSUE THREAD

**Issue by piotrkochan** [xo/dburl#13]
```
redis://[pass@][ip\|host\|socket[:port]][/db-index]

**Comment by kenshaw** [comment]
Is there a standard Go `sql` driver for redis? If not, I won't be adding it to `dburl`. Please note, if you want `redis://` compatible URLs, just use `net/url.Parse` to parse it, which is what `dburl` does.

**Comment by piotrkochan** [comment]
Ok
