### ISSUE TITLE
Error parsing mysql DSN

### ISSUE THREAD

**Issue by llorllale** [xo/dburl#15]
DSN: `mysql://root:secret@tcp(localhost:3306)/mysql`

Error: `parse "mysql://root:secret@tcp(mysql:3306)/mysql": invalid port ":3306)" after host`

**Comment by kenshaw** [comment]
@llorllale -- the DSN you have is not a proper URL. The form you want is:

```
mysql://root:secret@localhost:3306/mysql
```

To explain, `dburl` puts all database connection strings (DSNs) into standard URL form, which equates to:

```
scheme://user:pass@host:port/database?opt1=a&opt2=b
```
Where `scheme` is the protocol (ie, `mysql` or `postgres` or `mssql`, etc), and `database` is the name of the database. The other fields (also called URL components) are the same as any standard URL you might use in your web browser. 

I believe the form you're passing is the format that MySQL natively recognizes -- this format won't work with `dburl`. If you want to accept URLs in that format, and expect that you're only using MySQL, then `dburl` won't be of much help. In that case, you can simply pass the DSN string directly to your MySQL database driver.

Good luck with your project!
