### ISSUE TITLE
Add support for arbitrary protocols

### ISSUE THREAD

**Issue by josegonzalez** [xo/dburl#16]
It would be great to be able to support arbitrary protocols. My use case is having different backend drivers for a given scheme.

**Comment by kenshaw** [comment]
There's currently the `Register` func that allows the registration of any `Scheme` type. I don't know what else would be necessary, as this is what's used internally. Please see the `init()` func in `scheme.go` to see how the base schemes are registered.

**Comment by josegonzalez** [comment]
Didn't realize that was there. Thanks!
