### ISSUE TITLE
Modify the query parameters?

### ISSUE THREAD

**Issue by matthewmueller** [xo/dburl#25]
I was wondering if there's anyway to add query parameters with `dburl` other than parsing twice?

My use case is always adding some pragmas to the SQLite path.

```go
// Parse the dbPath, in this case sqlite::memory:
url, err := dburl.Parse(dbPath)
if err != nil {
	return nil, err
}

// Add _foreign_keys pragma
values := url.Query()
values.Set("_foreign_keys", "on")
url.RawQuery = values.Encode()

// url.DSN wasn't updated
db, err := sql.Open("sqlite3", url.DSN)
if err != nil {
	return nil, err
}
```

**Comment by matthewmueller** [comment]
I thinkkk this might work actually:

```go
db, err := sql.Open("sqlite3", url.DSN)
if err != nil {
	return nil, err
}
```

**Comment by kenshaw** [comment]
@matthewmueller note that this works just fine:
```
ken@ken-mbp:~$ usql sqlite://:memory:?_fk=true
Connected with driver sqlite3 (SQLite3 3.39.4)
Type "help" for help.

sq::memory:=> pragma foreign_keys;
 foreign_keys
--------------
            1
(1 row)

sq::memory:=>
```

**Comment by matthewmueller** [comment]
Hey @kenshaw, sorry I should have been more specific. 

I'd like to use dburl as a library for parsing connection strings in a standardized way.

Upfront parsing of a database path with query parameters works as you'd expect where `url.DSN` is set appropriately.

However, if you modify the query parameters after parsing, `url.DSN` is outdated. I was looking for a way to add query parameters after already parsing.

Closing though since `url.DSN+"?"+url.RawQuery` should cover it!

**Comment by matthewmueller** [comment]
Actually re-opening, I think `url.DSN+"?"+url.RawQuery` would not work as expected if you did something like:

```go
url, err := dburl.Parse(`sqlite://:memory:?mode=rwc`)
if err != nil {
	return nil, err
}

// Add _foreign_keys pragma
values := url.Query()
values.Set("_foreign_keys", "on")
url.RawQuery = values.Encode()

// url.DSN wasn't updated
db, err := sql.Open("sqlite3", url.DSN+"?"+url.RawQuery)
if err != nil {
	return nil, err
}
```

**Comment by kenshaw** [comment]
@matthewmueller Sorry I never replied to this before. You would need to reparse the URL with `dburl` if you add a query string.
