### ISSUE TITLE
Fails to parse passwords with '#' for mssql.

### ISSUE THREAD

**Issue by Ivan-Viktorov** [xo/dburl#3]
Tried with usql:
usql "ms://user:pw#d@mssql-server.local/base"
error: invalid port

This happens only with mssql. For postgres and mysql '#' doesn't cause any errors.

**Comment by kenshaw** [comment]
You probably need to URL encode the # symbol then.

**Comment by mindreframer** [comment]
@kenshaw this should be in the Readme for usql and xo - Gotchas section. I have spend some hours yesterday trying to work around that issue with various escaping strategies... URL encoding did not occur to me! ))) thx, it seem to be connecting now. Query parsing for MSSQL seem to be still broken, but that is something else...

**Comment by mindreframer** [comment]
Or even  better: shouldn't dburl apply the URL escaping before splitting the DSN? That would solve the issue

**Comment by Pritesh-Patel** [comment]
Ran into this issue too. Only worked out what to do from this issue.

**Comment by clearcodecn** [comment]
same issue. can we fix that, don't use net/url to parse.

**Comment by bmrobin** [comment]
if a fix isn't something you're interested in, then maybe just call it out in the README? i ran into this as well and it took a while to track down.

**Comment by nineinchnick** [comment]
Could you suggest a change in the Readme in a pull request?

**Comment by kenshaw** [comment]
I understand the frustration, but this is the rules of URL parsing. Additionally, `dburl` is simply using Go's underlying `net/url` package, and is only wrapping some very minor / additional logic around `net/url.URL`. The idea/concept for `dburl` comes from a number of other database packages/libraries in other programming languages, and I believe all have the same issue when it comes to special characters in passwords.
