### ISSUE TITLE
UNIX socket path should support URL encoding

### ISSUE THREAD

**Issue by caseyandgina** [xo/dburl#39]
```
$ psql "postgres://postgres@/run/postgresql/postgres"
psql: error: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "run/postgresql/postgres" does not exist
```

```
$ psql "postgres://postgres@%2Frun%2Fpostgresql/postgres"
psql (16.3 (Ubuntu 16.3-1.pgdg24.04+1))
Type "help" for help.

postgres=#
```

The above behavior is typical with applications that support URI database connection strings, including libpq itself.  However, with dburl, the former unescaped socket path works, while the escaped version does not, which is the opposite of usual.

**Comment by kenshaw** [comment]
I can appreciate the motivation to be compatible with `psql`, but I think `psql` here is doing the wrong thing. `dburl` simply wraps `net/url.URL`, and thus all URL parsing rules are actually upstream of this project. For certain security reasons, I do not think it wise to try to unescape paths when trying actual paths on disk.

**Comment by kenshaw** [comment]
`dburl` is meant to support `usql` and `xo`, and I do not see this as necessary, specifically because you have the ability to do this: `postgresql:///dbname?host=/var/lib/postgresql`, which of course would be respected by the URL parser.
