### ISSUE TITLE
Can't register scheme starting with "my"

### ISSUE THREAD

**Issue by dolmen** [xo/dburl#5]
I would like to contribute a scheme for my driver called `mylogin` (see package [`github.com/dolmen-go/mylogin-driver/register`](https://godoc.org/github.com/dolmen-go/mylogin-driver/register).
I've started to code the integration, but I'm blocked by the following error:

```
panic: scheme my already registered

goroutine 1 [running]:
github.com/xo/dburl.registerAlias(0x1142ef4, 0x7, 0x1142ef4, 0x2, 0xc420089b00)
	.../src/github.com/xo/dburl/scheme.go:119 +0x3b7
github.com/xo/dburl.Register(0x1142ef4, 0x7, 0x114ca10, 0x0, 0x1, 0x0, 0x0, 0x0, 0x11425b0, 0x0)
	.../src/github.com/xo/dburl/scheme.go:167 +0x422
github.com/xo/dburl.init.0()
	.../src/github.com/xo/dburl/scheme.go:100 +0xee
FAIL	github.com/xo/dburl	0.010s
Error: Tests failed.
```

It appears that I can't register a second scheme that starts with the same 2 first letters as an existing scheme (scheme `mysql` is also automatically registered as `my`).

I think that this restriction should be removed: if a scheme has not defined a short name and a short name with the 2 letter prefix already exists, just skip registration of that auto-generated short name.

**Comment by dolmen** [comment]
Workaround: force a short name (`ml` for my case).

**Comment by kenshaw** [comment]
`my` is registered to the mysql driver.

**Comment by dolmen** [comment]
@kenshaw Please reply to this: 
> I think that this restriction should be removed: if a scheme has not defined a short name and a short name with the 2 letter prefix already exists, just skip registration of that auto-generated short name.
