### ISSUE TITLE
Parse for {postgres,mysql}+unix schemes depend on filesystem state

### ISSUE THREAD

**Issue by dolmen** [xo/dburl#8]
Parsing of Postgres and MySQL schemes with a file path have different behavior depending if an element of the path exists on the filesystem and has specific properties. See functions `resolveDir` and `resolveSocket` in `util.go`.
This inconsistent behavior of `Parse` makes connection failures harder to debug. Worse: this behavior is not documented.

In general, it is very bad that a function called `Parse` has different results depending on the filesystem state, as it is not expected by a developer using this API.

Related to #6.

**Comment by kenshaw** [comment]
This behavior is intended, and the behavior is documented in `README.md`.
